import { GoogleSpreadsheet } from 'google-spreadsheet';
import { StockPosition } from '../types/Position';

import { PRIVATE_KEY, CLIENT_EMAIL, GG_SPREADSHEET_ID } from './auth';

const SHEET_TITLE = 'Positions';

export const emptyPosition: StockPosition = {
  marketID: '',
  instrumentID: '',
  onHand: 0,
  block: 0,
  bonus: 0,
  buyT0: 0,
  buyT1: 0,
  buyT2: 0,
  sellT0: 0,
  sellT1: 0,
  sellT2: 0,
  avgPrice: 0,
  mortgage: 0,
  sellableQty: 0,
  holdForTrade: 0,
  marketPrice: 0,
  total: 0,
  value: 0,
  allocation: 0,
  target: 0,
  buying: false,
  delta: 0,
};

const getEmptyValue = (value: number, isEmpty: boolean) => {
  if (isEmpty) return '';
  return value;
};

const fillEmptyRow = (positions: StockPosition[], maxRow: number) => {
  const arr = [];
  for (let i = 0; i < maxRow; i++) {
    arr.push(positions[i] || emptyPosition);
  }
  return arr;
};

export const savePositionsToGG = async (positionsOrg: StockPosition[]) => {
  const positions = fillEmptyRow(positionsOrg, 100);
  console.log('savePositionsToGG', positionsOrg.length);

  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet(GG_SPREADSHEET_ID);

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: CLIENT_EMAIL,
    private_key: PRIVATE_KEY,
  });

  // loads document properties and worksheets
  await doc.loadInfo();
  const sheet = doc.sheetsByTitle[SHEET_TITLE];

  if (!sheet) {
    return -1;
  }

  await sheet.loadCells(`A2:E${positions.length + 2}`);

  for (let i = 0; i < positions.length; i++) {
    const cellIndex = i + 2;
    const position = positions[i];
    const isEmpty = !position.instrumentID;
    const now = Date.now();

    const symbol = sheet.getCellByA1(`A${cellIndex}`);
    const sellableQty = sheet.getCellByA1(`B${cellIndex}`);
    const total = sheet.getCellByA1(`C${cellIndex}`);
    const avgPrice = sheet.getCellByA1(`D${cellIndex}`);
    const timestamp = sheet.getCellByA1(`E${cellIndex}`);

    symbol.value = position.instrumentID;
    sellableQty.value = getEmptyValue(position.sellableQty, isEmpty);
    total.value = getEmptyValue(position.total, isEmpty);
    avgPrice.value = getEmptyValue(position.avgPrice, isEmpty);
    timestamp.value = getEmptyValue(now, isEmpty);
  }

  await sheet.saveUpdatedCells();
  return 0;
};
