/** Declaration file generated by dts-gen */
declare module 'ssi-api-client';

export const api: {
  CANCEL_ORDER: string;
  GET_ACCESS_TOKEN: string;
  GET_ACCOUNT_BALANCE: string;
  GET_DER_ACCOUNT_BALANCE: string;
  GET_DER_POSITION: string;
  GET_MAX_BUY_QUANTITY: string;
  GET_MAX_SELL_QUANTITY: string;
  GET_ORDER_HISTORY: string;
  GET_OTP: string;
  GET_PPMMRACCOUNT: string;
  GET_STOCK_POSITION: string;
  MODIFY_ORDER: string;
  NEW_ORDER: string;
  SIGNALR: string;
};

export const constants: {
  AUTHORIZATION_HEADER: string;
  AUTHORIZATION_SCHEME: string;
  SIGNATURE_HEADER: string;
};

export const events: {
  onClientPortfolioEvent: string;
  onError: string;
  onOrderError: string;
  onOrderMatch: string;
  onOrderUpdate: string;
};

export const streamClient: {};

export function bind(event: any, func: any): void;

export function initStream(options: any): void;

export function sign(data: any, private_key: any): any;

export function start(): void;

export function unbind(event: any, func: any): void;
