import { GoogleSpreadsheet } from 'google-spreadsheet';
import { isEqual } from 'lodash';
import { MarketConfig } from '../types/market-config';

import { PRIVATE_KEY, CLIENT_EMAIL, GG_SPREADSHEET_ID } from './auth';

const SHEET_TITLE = 'markets';
const UPDATE_INTERVAL = 30000;

export const loadStrategies = async (): Promise<MarketConfig[]> => {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet(GG_SPREADSHEET_ID);

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: CLIENT_EMAIL,
    private_key: PRIVATE_KEY,
  });

  // loads document properties and worksheets
  await doc.loadInfo();
  const sheet = doc.sheetsByTitle[SHEET_TITLE];

  if (!sheet) {
    return [];
  }

  const rows = await sheet.getRows();
  return rows.map((i) => {
    return {
      asset: i.Asset,
      symbol: i.Symbol,
    };
  });
};

export const onStrategyChange = async (
  callback: (l: MarketConfig[]) => void,
) => {
  let oldList = await loadStrategies();

  setInterval(async () => {
    const newList = await loadStrategies();
    if (!isEqual(oldList.sort(), newList.sort())) {
      oldList = newList;
      callback(newList);
    }
  }, UPDATE_INTERVAL);
};
